# -*- coding: utf-8 -*-
"""Assignment 1 IDC 122.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18u3SWZ4I-IR9zGtXeEhMoY-DO6Nu3fRn

$$ \mathrm{Assignment \ 1} $$
$$ \mathrm{IDC-122}$$
$$ \mathrm{Vasanth \ \ 2025}$$


Deadline : 15/02/25


---

## Instructions
1. Write C programs for the following problems.
2. Use comments in your code to explain your logic.
3. Test your programs with different inputs to ensure they work correctly.
4. Submit your code as `.c` files with appropriate filenames (e.g., `file_creation.c`, `summation.c`, etc.).


## Problem 1: Pointers and File Handling
1.1) Write a C program that creates a file called `numbers.txt`. The file will contain any 5 numbers of your choice.

1.2) Write another C program that reads a list of numbers from a text file and prints their sum.

**Requirements:**
- Create the `numbers.txt` file.
- Read numbers from a file `numbers.txt`.
- Traverse the array of numbers in the file, and calculate the sum.
- Print the sum to the console and write the result to `output.txt`.


## Problem 2: Numerical Differentiation
Write a C program to compute the derivative of a function using the backward difference formula.

$$ f'(x) = \frac{f(x) - f(x-h)}{h} $$

**Requirements:**
- Use the function: `f(x) = x^3 - 4x + 1`.
- Take `x` and `h` (step size) as input.
- Compute the derivative using backward difference formula.
- Compare the results with the actual derivative `f'(x) = 3x^2 - 4`.


---

### Submission Guidelines
- Ensure your code is well-commented and properly indented.
- Test each program before submission and include example inputs and outputs in your README.
- Submit your assignment as a compressed `.zip` file containing all C source files(.c files) and `README.txt`.
- The name of your zip file should be in the following manner: `YOUR_NAME_YOUR_ROLLNO_IDC122_Assignment1.zip`
- Upload it to the classroom assignment.

**P.S.** - This assignment is intended to help you recall and exercise your concepts in pointers, and numerical method implementation using an equation. Write whatever code you can by yourself. Do not copy from other students, or other online / AI resources. The later approach will result in me rejecting your assignment submission. There will be stepwize marks for incomplete codes as well, so do not worry if your code does not execute properly.
"""

