# -*- coding: utf-8 -*-
"""IDC 122 Pointers and File handling _ Second Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128BQ3kTNPQtqEuCJI_1o4fH9gnO-PZrE

# Understanding Pointers in C

Pointers are one of the most powerful features in C programming. We will explore how pointers work, how to declare and use them, and how they can be dereferenced to access or modify the values they point to.



## Key Concepts Explained

### 1. **What is a Pointer?**
A pointer is a variable that stores the memory address of another variable.
- The syntax for declaring a pointer is: `type *pointerName;`.
- For example, `int *pAge;` declares a pointer to an integer.

### 2. **The Address-of Operator (`&`)**
The address-of operator (`&`) is used to retrieve the memory address of a variable. For example:
```c
int age = 21;
int *pAge = &age; // pAge now stores the address of age
```

### 3. **The Indirection (Dereference) Operator (`*`)**
The indirection operator (`*`) is used to access the value at the memory address stored in a pointer. For example:
```c
printf("%d", *pAge); // Prints the value stored at the address pAge points to
```

---

### Function: `printAge`
```c
void printAge(int *pAge)
{
   printf("You are %d years old\n", *pAge); // dereference
}
```
This function takes a pointer to an integer (`int *pAge`) as an argument. It dereferences the pointer using `*pAge` to access the value it points to and prints it.

### Main Function

#### Step 1: Declare a Variable and a Pointer
```c
int age = 21;
int *pAge = &age;
```
- `age` is a regular integer variable storing the value `21`.
- `pAge` is a pointer that stores the address of `age` (obtained using `&age`).

#### Step 2: Call the `printAge` Function
```c
printAge(pAge);
```
The pointer `pAge` is passed to the function, which uses it to print the value of `age`.

#### Step 3: Print Memory and Pointer Details

1. **Address of the Variable**
```c
printf("address of age: %p\n", &age);
```
Prints the memory address of `age`.

2. **Value of the Pointer**
```c
printf("value of pAge: %p\n", pAge);
```
Prints the address stored in `pAge`, which is the same as `&age`.

3. **Size of Variables**
```c
printf("size of age: %d bytes\n", sizeof(age));
printf("size of pAge: %d bytes\n", sizeof(pAge));
```
- Prints the size of `age` (typically 4 bytes for an `int`).
- Prints the size of `pAge` (typically 8 bytes on 64-bit systems).

4. **Value of the Variable**
```c
printf("value of age: %d\n", age);
```
Prints the value stored in `age` (21).

5. **Dereference the Pointer**
```c
printf("value at stored address: %d\n", *pAge);
```
Dereferences `pAge` to access and print the value stored at the memory address it points to (21).

---

## Output
When you run the program, you will see output similar to the following:
```
You are 21 years old
address of age: 0x7ffee3a2b5dc
value of pAge: 0x7ffee3a2b5dc
size of age: 4 bytes
size of pAge: 8 bytes
value of age: 21
value at stored address: 21
```



---

## Complete code


```c
void printAge(int *pAge)
{
   printf("You are %d years old\n", *pAge); // dereference
}

int main()
{
   // pointer = a "variable-like" reference that holds a memory address to another variable, array, etc.
   //           some tasks are performed more easily with pointers
   //           * = indirection operator (value at address)

   int age = 21;
   int *pAge = &age;

   printAge(pAge);

   printf("address of age: %p\n", &age);
   printf("value of pAge: %p\n", pAge);
   printf("size of age: %d bytes\n", sizeof(age));
   printf("size of pAge: %d bytes\n", sizeof(pAge));
   printf("value of age: %d\n", age);
   printf("value at stored address: %d\n", *pAge); // dereferencing

   return 0;
}
```

---


## Summary

- **Pointers** are variables that store memory addresses.
- The `&` operator is used to get the memory address of a variable.
- The `*` operator is used to dereference a pointer to access the value it points to.
- Pointers are essential in C for efficient memory management and advanced programming tasks.

---

## Exercise
Create a new function that swaps the values of two variables using pointers.
"""

#include <stdio.h>

int main() {
    FILE *file = fopen("example.txt", "w"); // Open file in write mode

    if (file == NULL) {
        printf("Error opening file!\n");
        return 1;
    }

    fprintf(file, "Hello, File Handling in C!\n"); // Write to the file
    fclose(file); // Close the file

    printf("Data written successfully.\n");
    return 0;
}

"""# File Handling in C

File handling is a crucial aspect of programming that allows data to be stored, retrieved, and manipulated in files.


### Common File Operations
1. **Creating a file**
2. **Opening a file**
3. **Writing data to a file**
4. **Reading data from a file**
5. **Closing a file**

---

## File Operations in C

### File Modes
When working with files, you specify a mode to indicate the operation to be performed. Here are the most commonly used modes:

| Mode | Description |
|------|-------------|
| `"r"`  | Open for reading (file must exist). |
| `"w"`  | Open for writing (creates a new file or truncates an existing file). |
| `"a"`  | Open for appending (data is added to the end of the file). |
| `"r+"` | Open for both reading and writing. |
| `"w+"` | Open for both reading and writing (overwrites file if it exists). |
| `"a+"` | Open for both reading and appending. |

### File Handling Functions
- **`fopen`**: Opens a file and returns a file pointer.
- **`fclose`**: Closes an opened file.
- **`fprintf`**: Writes formatted data to a file.
- **`fscanf`**: Reads formatted data from a file.
- **`fputs` / `fgets`**: Write and read strings to/from a file.
- **`fwrite` / `fread`**: Write and read binary data to/from a file.

---

## Code Examples

### Example 1: Writing to a File
```c
#include <stdio.h>

int main() {
    FILE *file = fopen("example.txt", "w"); // Open file in write mode

    if (file == NULL) {
        printf("Error opening file!\n");
        return 1;
    }

    fprintf(file, "Hello, File Handling in C!\n"); // Write to the file
    fclose(file); // Close the file

    printf("Data written successfully.\n");
    return 0;
}
```

#### Output
- A file named `example.txt` is created with the content:
```
Hello, File Handling in C!
```

---

### Example 2: Reading from a File
```c
#include <stdio.h>

int main() {
    FILE *file = fopen("example.txt", "r"); // Open file in read mode

    if (file == NULL) {
        printf("Error opening file!\n");
        return 1;
    }

    char buffer[100];
    while (fgets(buffer, sizeof(buffer), file) != NULL) {
        printf("%s", buffer); // Print each line read from the file
    }

    fclose(file); // Close the file
    return 0;
}
```

#### Output
The content of `example.txt` is printed to the console:
```
Hello, File Handling in C!
```

---

### Example 3: Appending Data to a File
```c
#include <stdio.h>

int main() {
    FILE *file = fopen("example.txt", "a"); // Open file in append mode

    if (file == NULL) {
        printf("Error opening file!\n");
        return 1;
    }

    fprintf(file, "Appending this line to the file.\n"); // Append to the file
    fclose(file); // Close the file

    printf("Data appended successfully.\n");
    return 0;
}
```

#### Output
The file `example.txt` now contains:
```
Hello, File Handling in C!
Appending this line to the file.
```

---

### Example 4: Reading and Writing Binary Data
```c
#include <stdio.h>

int main() {
    FILE *file;
    int data[] = {10, 20, 30, 40, 50};
    int readData[5];

    // Write binary data
    file = fopen("data.bin", "wb");
    fwrite(data, sizeof(int), 5, file);
    fclose(file);

    // Read binary data
    file = fopen("data.bin", "rb");
    fread(readData, sizeof(int), 5, file);
    fclose(file);

    printf("Data read from binary file: ");
    for (int i = 0; i < 5; i++) {
        printf("%d ", readData[i]);
    }
    printf("\n");

    return 0;
}
```

#### Output
```
Data read from binary file: 10 20 30 40 50
```

---

## Error Handling in File Operations
Always check if the file pointer is `NULL` to handle errors, such as when the file does not exist or cannot be opened due to permission issues.

```c
FILE *file = fopen("nonexistent.txt", "r");
if (file == NULL) {
    perror("Error opening file");
    return 1;
}
```
"""



"""

```
# This is formatted as code
```

"""

#include<stdio.h>



"""### Solution:

```c
#include <stdio.h>

// Function to swap two integers using pointers
void swap(int *a, int *b)
{
    int temp = *a; // Store the value at address 'a' in a temporary variable
    *a = *b;       // Assign the value at address 'b' to address 'a'
    *b = temp;     // Assign the temporary value to address 'b'
}

int main()
{
    int x = 5, y = 10;

    printf("Before swapping: x = %d, y = %d\n", x, y);
    
    // Call the swap function with pointers to x and y
    swap(&x, &y);
    
    printf("After swapping: x = %d, y = %d\n", x, y);

    return 0;
}

```
"""