# -*- coding: utf-8 -*-
"""class-4-IDC 122 Scientific computation in C++.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107keRLyLd7XOfDn6hhWQGbxygodfOx-t

## IDE and Setting Up the Environment

An **IDE**, or Integrated Development Environment, is a software application that provides a comprehensive environment for software development, combining tools like code editors, compilers, debuggers, and build automation tools into a single interface, streamlining the development process


- **Using VS Code:**  
  For this tutorial, we will use [VS Code](https://code.visualstudio.com/) as our development environment.
  

- **Code Organization Tips:**  
  - Organize your code into separate files (e.g., `.cpp` for implementation and `.h` for headers).
  - Use comments generously to explain each part of your code.
  - Regularly compile and test your code to catch errors early.

---

### A. Basic Mathematical Computations

#### Example 1: Calculating the Area of a Circle

This simple program calculates the area of a circle using a function.

```cpp
#include <iostream>
#define PI 3.14159

// Function to calculate the area of a circle
double calculateCircleArea(double radius) {
    return PI * radius * radius;
}

int main() {
    double radius;
    std::cout << "Enter the radius of the circle: ";
    std::cin >> radius;

    double area = calculateCircleArea(radius);
    std::cout << "The area of the circle is: " << area << std::endl;

    return 0;
}
```


#### Example 2: Computing Gravitational Force

This example calculates the gravitational force between two objects.

```cpp
#include <iostream>
#define G 6.67430e-11 // Gravitational constant

// Function to calculate gravitational force
double calculateGravitationalForce(double mass1, double mass2, double distance) {
    return (G * mass1 * mass2) / (distance * distance);
}

int main() {
    double mass1, mass2, distance;
    std::cout << "Enter mass of object 1 (in kg): ";
    std::cin >> mass1;
    std::cout << "Enter mass of object 2 (in kg): ";
    std::cin >> mass2;
    std::cout << "Enter the distance between objects (in meters): ";
    std::cin >> distance;

    double force = calculateGravitationalForce(mass1, mass2, distance);
    std::cout << "The gravitational force is: " << force << " N" << std::endl;

    return 0;
}
```


---

### B. Algorithmic Problem Solving

#### Example 3: Approximating π using the Leibniz Formula

This program uses a loop to approximate π by summing the Leibniz series.

\begin{equation}
\frac{π}{4} = 1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} + ... = \sum_{k=0}^{∞} \frac{(-1)^k}{2k+1}
\end{equation}

```cpp
#include <iostream>

// Function to approximate π using the Leibniz formula
double approximatePi(int iterations) {
    double pi = 0.0;
    for (int i = 0; i < iterations; ++i) {
        // Alternate between addition and subtraction
        if (i % 2 == 0)
            pi += 1.0 / (2 * i + 1);
        else
            pi -= 1.0 / (2 * i + 1);
    }
    return 4 * pi;
}

int main() {
    int iterations;
    std::cout << "Enter the number of iterations for approximation: ";
    std::cin >> iterations;

    double piValue = approximatePi(iterations);
    std::cout << "Approximated value of π is: " << piValue << std::endl;

    return 0;
}
```


---

## Introducing Object-Oriented Programming in a Scientific Context

### A. Modeling Scientific Instruments

#### Example 4: Base Class and Derived Classes for Scientific Instruments

This example defines a base class for a generic scientific instrument and derives specific instruments from it.

```cpp
#include <iostream>
#include <string>

// Base class for a scientific instrument
class Instrument {
protected:
    std::string name;
    double accuracy;
public:
    Instrument(const std::string& n, double a) : name(n), accuracy(a) {}
    // string& prevents making a copy of n while printing

    // Virtual function to simulate measurement
    virtual void measure() const {
        std::cout << "Measuring with " << name << " with accuracy " << accuracy << std::endl;
    }
};

// Derived class for a Thermometer
class Thermometer : public Instrument {
public:
    Thermometer(double a) : Instrument("Thermometer", a) {}

    // Override the measure function
    void measure() const override {
        std::cout << "Measuring temperature with accuracy " << accuracy << "°C." << std::endl;
    }
};

// Derived class for a Barometer
class Barometer : public Instrument {
public:
    Barometer(double a) : Instrument("Barometer", a) {}

    // Override the measure function
    void measure() const override {
        std::cout << "Measuring atmospheric pressure with accuracy " << accuracy << " hPa." << std::endl;
    }
};

int main() {
    Thermometer thermo(0.1);
    Barometer baro(0.5);

    thermo.measure();
    baro.measure();

    return 0;
}
```

### B. Simulation: Projectile Motion

#### Example 5: Simple Projectile Motion Simulation

This example simulates projectile motion using basic physics equations within an object-oriented framework.

```cpp
#include <iostream>
#include <cmath>

// Base class representing a moving object
class MovingObject {
protected:
    double velocity;
    double angle; // in degrees
public:
    MovingObject(double v, double a) : velocity(v), angle(a) {}

    // Function to compute horizontal distance given time
    double horizontalDistance(double time) const {
        return velocity * std::cos(angle * M_PI / 180.0) * time;
    }

    // Function to compute vertical distance given time
    double verticalDistance(double time, double gravity = 9.81) const {
        return velocity * std::sin(angle * M_PI / 180.0) * time - 0.5 * gravity * time * time;
    }
};

int main() {
    double initialVelocity, launchAngle;
    std::cout << "Enter initial velocity (m/s): ";
    std::cin >> initialVelocity;
    std::cout << "Enter launch angle (degrees): ";
    std::cin >> launchAngle;

    MovingObject projectile(initialVelocity, launchAngle);

    double time;
    std::cout << "Enter time (seconds) to evaluate position: ";
    std::cin >> time;

    double x = projectile.horizontalDistance(time);
    double y = projectile.verticalDistance(time);

    std::cout << "At time " << time << " seconds:" << std::endl;
    std::cout << "Horizontal Distance: " << x << " meters" << std::endl;
    std::cout << "Vertical Distance: " << y << " meters" << std::endl;

    return 0;
}
```

---
"""

